### ISSUE TITLE
overwhelmed by error logs

### ISSUE THREAD

**Issue by TrejGun** [nestjs/passport#1173]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

After recent update my log is overwhelmed by errors which was not there before

```
Error: No auth token
at FirebaseStrategy.FirebaseJwtStrategy.authenticate ([/node_modules/passport-firebase-jwt/lib/strategy.js:40:26)
at attempt ([/node_modules/passport/lib/middleware/authenticate.js:369:16)
at authenticate ([/node_modules/passport/lib/middleware/authenticate.js:370:7)
at [/node_modules/@nestjs/passport/dist/auth.guard.js:100:3
at new Promise (<anonymous>)
at [/node_modules/@nestjs/passport/dist/auth.guard.js:92:83
at FirebaseHttpGuard.<anonymous> ([/node_modules/@nestjs/passport/dist/auth.guard.js:50:36)
at Generator.next (<anonymous>)
at fulfilled ([/node_modules/@nestjs/passport/dist/auth.guard.js:17:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

here is a line of code which throws error

https://github.com/Mawi137/passport-firebase-jwt/blob/master/lib/strategy.js#L40

but not having a token in request is a normal situation, not all my routes are protected some of them are public, and I use techniqueue from this article

https://dev.to/dannypule/exclude-route-from-nest-js-authgaurd-h0

this is not the only affected library, for example this library also throws error on the same condition

https://github.com/maisquestoes/passport-apikey/blob/master/lib/passport-apikey/strategy.js#L76

please rollback this commit
https://github.com/nestjs/passport/commit/fa68aa6305e57f756a93a5cbd157d28cc365bfb8

### Minimum reproduction code

```ts

```

### Expected behavior

no output

### Other

qwe

**Comment by kamilmysliwiec** [comment]
Maybe we should change it from `.error()` to `.debug()` just so it's easy to turn it off (especially in prod)? 🤔

**Comment by TrejGun** [comment]
thanks a lot

**Comment by sezanzeb** [comment]
I wish this was changed to `.debug()` instead. The proposed alternative of monkey-patching it is considered bad practice afaik...

**Comment by sezanzeb** [comment]
> If anyone needs more verbose logging they can just override the handleRequest method.

> The proposed alternative of monkey-patching it is considered bad practice afaik...

I misunderstood this, handleRequest can be overwritten in the class inheriting from `AuthGuard(...)` as far as I can tell.

I would still prefer a debug log which is there by default. Without your remark I wouldn't have realized that this can be overwritten

**Comment by kamilmysliwiec** [comment]
This is documented here https://docs.nestjs.com/recipes/passport#extending-guards
