### ISSUE TITLE
UnauthorizedException lacks detailed error message in @nestjs/passport

### ISSUE THREAD

**Issue by System233** [nestjs/passport#1707]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I encountered an issue with the @nestjs/passport package where the error message for UnauthorizedException is too generic and does not provide detailed information about the cause of the exception. This makes debugging difficult.

Steps to Reproduce:

Implement JWT authentication using @nestjs/passport and passport-jwt.
Configure a JWT strategy and guard.
Trigger an authentication failure by providing an invalid or expired JWT token.

Observed Behavior:
The error message logged is:
```log
 [Nest] 1  - 07/17/2024, 8:32:28 PM   ERROR [RpcExceptionsHandler] Unauthorized
 UnauthorizedException: Unauthorized
     at JwtAuthGuard.handleRequest (/app/node_modules/@nestjs/passport/dist/auth.guard.js:61:30)
     at /app/node_modules/@nestjs/passport/dist/auth.guard.js:44:124
     at /app/node_modules/@nestjs/passport/dist/auth.guard.js:84:24
     at allFailed (/app/node_modules/passport/lib/middleware/authenticate.js:110:18)
     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:183:28)
     at strategy.fail (/app/node_modules/passport/lib/middleware/authenticate.js:314:9)
     at /app/node_modules/passport-jwt/lib/strategy.js:106:33
     at /app/node_modules/jsonwebtoken/verify.js:190:16
     at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
     at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
```

### Describe the solution you'd like

Expected Behavior:
The error message should provide more context about why the authentication failed, such as whether the token is invalid, expired, or if there was an issue with token signature verification.

### What is the motivation / use case for changing the behavior?

Cause Analysis:
The issue is caused by @nestjs/passport suppressing underlying JWT errors, such as expiration or invalid token errors, resulting in a non-descriptive UnauthorizedException: Unauthorized error.

First passport passes null,false as err and user parameters respectively https://github.com/jaredhanson/passport/blob/0575de90dc0e76c1b8ca9cc676af89bd301aec60/lib/middleware/authenticate.js#L107-L116 
Then `auth.guard.ts` simply throws err or UnauthorizedException and ignores the info error message https://github.com/nestjs/passport/blob/c6e51abde408801f7a23bf1c2aff683ee0d5a138/lib/auth.guard.ts#L96-L101

The following changes are desired:
```ts
    handleRequest(err, user, info, context, status): TUser {
      if (err || !user) {
        throw err || new UnauthorizedException(info);
      }
      return user;
    }
```
```log
[Nest] 1  - 07/17/2024, 8:50:18 PM   ERROR [RpcExceptionsHandler] jwt expired
UnauthorizedException: jwt expired
    at JwtAuthGuard.handleRequest (/app/node_modules/@nestjs/passport/dist/auth.guard.js:61:30)
    at /app/node_modules/@nestjs/passport/dist/auth.guard.js:44:124
    at /app/node_modules/@nestjs/passport/dist/auth.guard.js:84:24
    at allFailed (/app/node_modules/passport/lib/middleware/authenticate.js:110:18)
    at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:183:28)
    at strategy.fail (/app/node_modules/passport/lib/middleware/authenticate.js:314:9)
    at /app/node_modules/passport-jwt/lib/strategy.js:106:33
    at /app/node_modules/jsonwebtoken/verify.js:190:16
    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
    at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
```

**Comment by System233** [comment]
SORRY #1695 
But I have an issue about RMQ and authentication, I will talk about it later
