### ISSUE TITLE
Nest can't resolve dependencies of the JwtAuthenticationGuard after upgrade 8.1.0 to 8.1.1

### ISSUE THREAD

**Issue by rvieceli** [nestjs/passport#823]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

After upgrade nest, in special `@nestjs/passport`, it started to throw an exception. Going back to 8.1.0 it works again.

The error
```
[Nest] 63736  - 14/02/2022, 17:05:19   ERROR [ExceptionHandler] Nest can't resolve dependencies of the JwtAuthenticationGuard. Please make sure that the "options" property is available in the current context.

Potential solutions:
- If AuthModuleOptions is a provider, is it part of the current EmailScheduleModule?
- If AuthModuleOptions is exported from a separate @Module, is that module imported within EmailScheduleModule?
  @Module({
    imports: [ /* the Module containing AuthModuleOptions */ ]
  })

Error: Nest can't resolve dependencies of the JwtAuthenticationGuard. Please make sure that the "options" property is available in the current context.

Potential solutions:
- If AuthModuleOptions is a provider, is it part of the current EmailScheduleModule?
- If AuthModuleOptions is exported from a separate @Module, is that module imported within EmailScheduleModule?
  @Module({
    imports: [ /* the Module containing AuthModuleOptions */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:202:19)
    at Injector.resolveComponentInstance (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:157:33)
    at /Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:260:38
    at async Promise.all (index 0)
    at Injector.resolveProperties (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:251:27)
    at callback (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:47:32)
    at Injector.resolveConstructorParams (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:124:24)
    at Injector.loadInstance (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadInjectable (/Users/rvieceli/Projects/study/nestjs/wanago.io-nestjs/node_modules/@nestjs/core/injector/injector.js:70:9)
    at async Promise.all (index 0)
```

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/2790845/153901042-a78545a8-b94e-499f-a3c9-a09e7364c83a.png">

### Minimum reproduction code

Look at my project https://github.com/rvieceli/wanago.io-nestjs

### Expected behavior

It doesn't depend on AuthModuleOptions

### Other

```
[System Information]
OS Version     : macOS Big Sur
NodeJS Version : v16.14.0
NPM Version    : 8.3.1 

[Nest CLI]
Nest CLI Version : 8.2.0 

[Nest Platform Information]
platform-express version : 8.3.0
elasticsearch version    : 8.0.0
schematics version       : 8.0.5
passport version         : 8.1.1
schedule version         : 1.0.2
typeorm version          : 8.0.3
testing version          : 8.2.6
common version           : 8.3.0
config version           : 1.2.0
core version             : 8.3.0
cqrs version             : 8.0.2
jwt version              : 8.0.0
cli version              : 8.2.0
```

**Comment by jmcdo29** [comment]
Okay, yeah, that tracks. I was using a single module setup for testing this. You would need to use the `PassportModule.register({})` and then have your `AuthModule` have `PassportModule` in the `exports` and ensure that `AuthModule` was imported wherever you use the `AuthGuard()`.

Turns out, I needed to add `@Optional()` to the property injector as well, so the fix is easy, it's just making sure our test suite is updated now

**Comment by jmcdo29** [comment]
Only if 
1) you have a `PassportModule.register()` with options you want to have used (like user property )
2) You have a guard that needs to `AuthService`

Otherwise, it shouldn't really be necessary, but it is at the moment because of the change

**Comment by jmcdo29** [comment]
@cleytoncoro if you'd read the above comments in the issue, and the linked PR, you'd realize this already has a fix, and there's solutions in the thread already. Kamil will most likely publish a patch or minor update for this once the PR is merged.

**Comment by kamilmysliwiec** [comment]
Fixed
